
/**
 * This file defines types for our Supabase database schema.
 * Since the autogenerated types from Supabase don't include our custom tables,
 * we're creating this file to provide proper type checking.
 */

// Add this to your existing types to access in the application
declare namespace Supabase {
  interface Profile {
    id: string;
    email?: string | null;
    full_name?: string | null;
    avatar_url?: string | null;
    address_line1?: string | null;
    address_line2?: string | null;
    city?: string | null;
    postcode?: string | null;
    country?: string | null;
    phone_number?: string | null;
    company_name?: string | null;
    trading_address?: string | null;
    is_two_factor_enabled?: boolean | null;
    feedback_rating?: number | null;
    annual_2fa_payment_date?: string | null;
    referred_by?: string | null;
    signup_date?: string | null;
    strike_count?: number | null;
    created_at: string;
    updated_at: string;
  }

  interface Listing {
    id: string;
    seller_id: string;
    title: string;
    description: string;
    category: string;
    type: string;
    price: number;
    location: string;
    condition: string;
    images: string[];
    allow_best_offer: boolean;
    expires_at: string;
    created_at: string;
    updated_at: string;
    status: string;
    views: number;
    saves: number;
  }

  interface SavedListing {
    id: string;
    user_id: string;
    listing_id: string;
    created_at: string;
    listings?: Listing;
  }

  interface Message {
    id: string;
    sender_id: string;
    receiver_id: string;
    listing_id?: string;
    content: string;
    is_read: boolean;
    created_at: string;
    has_contact_info: boolean;
    listings?: {
      id: string;
      title: string;
    };
    sender_profile?: {
      full_name: string;
    };
    receiver_profile?: {
      full_name: string;
    };
  }

  interface Notification {
    id: string;
    user_id: string;
    type: string;
    message: string;
    is_read: boolean;
    created_at: string;
    metadata?: {
      description?: string;
      [key: string]: any;
    };
  }

  interface Feedback {
    id: string;
    from_user_id: string;
    to_user_id: string;
    listing_id: string;
    rating: number;
    comment?: string;
    created_at: string;
  }

  interface UserRole {
    id: string;
    user_id: string;
    role: 'unverified' | 'verified' | 'admin';
  }

  // Define a conversation contact with user info and message stats
  interface Contact {
    id: string;
    full_name: string | null;
    avatar_url: string | null;
    latest_message: string;
    latest_timestamp: string;
    unread_count: number;
    user_id: string;
  }
}
